### PR TITLE
Completed mint.com sign-up section clone on Feature-Branch

### PR DESCRIPTION
**Pull request by Kyle-Law**
Completed mint.com sign-up section clone on Feature-Branch

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really nice work @Kyle-Law and @Daniduran-dev 
Your project is looking sweet, and you have just one small detail to address. Your terms and conditions section needs a little breathing space, right now, it is directly on top some parts of your form. Please give this another look then request a re-review.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by shshamim63** [comment]
## Status :eagle: [!! Required Changes !!] :eagle: 
___
Hi @Kyle-Law and @Daniduran-dev :wave: 
Code looks neat and clean, items are rendering on the place where they should. Checked HTML markup and it was not yelling any errors. Great job :clap: . But  one major issue is blocking me to approve this project. And I am sorry that it was not mentioned on the previous review.
___
#### Please follow the instruction below to complete this project.
___
### :spades: [!! Mandatory Changes !!] :spades: 
___
1. You were asked to setup a linter. On the [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/), section `Remember to` contains that instruct. So please setup the linter.
2. I can see a .DS_store file. It should not be there. So please add it to gitigronre.
___
### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](__ Shakhawat Hossain__)

**Review by fatymahmed — CHANGES_REQUESTED** [review]
HI @Kyle-Law  @Daniduran-dev,
Great job so far 👏👏,
- I noticed that you added stickler file but make sure you've enabled stickler in your repo, see [this](https://github.com/microverseinc/linters-config/tree/master/css) for more details on how to set up stickler.
- As mentioned in the previous review, you shouldn't commit files like DS_Store, good job adding it to .gitignore file, check [this](https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore) on how to remove the file from cache since you had already committed it before so it is cached.

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Please make the requested changes and request for another code review.
## Status: Changes Required

_Feel free to reach out to me on slack (fatima) if you need help or have any questions 😃_

**Comment by Kyle-Law** [comment]
There are no feedbacks but still, appear '1 failing check'. Please advise.

**Comment by fatymahmed** [comment]
> There are no feedbacks but still, appear '1 failing check'. Please advise.

Hi @Kyle-Law, it's showing that it's failing because you have some errors that you need to fix.
You can view those errors when you click on `checks` which is at the top of this Pull request.
See the screenshot below on where `check` is.
Screenshot


I hope this made it clear to you, otherwise reach out to me on slack (Fatima), I'd be happy to clarify it.

**Review by suretrust — APPROVED** [review]
Hi @Kyle-Law and @Daniduran-dev,

### Amazing job guys! :raised_hands: Let's get this merged. :+1: 

_Good luck with your future projects and happy coding!_ :tada:

**Comment by Kyle-Law** [comment]
Thanks, @Oluwadamilareolusakin , @suretrust, @shshamim63 , and @fatymahmed for reviewing our codes!
Hurray @Daniduran-dev !!

**Pull request merged**
